apiVersion: vitistack.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: team-viti-001-sdj3
spec:
  data:
    clusterUid: "b74f880a-8a35-4f13-a70a-0dd53d708781"
    clusterId: "team-viti-001-sdj3"
    provider: talos
    environment: dev
    datacenter: no-south-az1
    project: simple-project
    region: south
    workorder: "simple-workorder"
    zone: "az1"
    workspace: "simple-workspace"
    networkNamespaceName: team-viti
  topology:
    version: "1.35.0"
    controlplane:
      replicas: 1
      version: "1.35.0"
      machineClass: small # Should provide 4 vCPUs, 4 GiB RAM
      provider: kubevirt
      storage:
        - class: "standard"
          path: "/var/lib/vitistack/kubevirt"
          size: "20Gi" # Talos recommended for production
      metadata:
        annotations:
          environment: development
          region: south
        labels:
          environment: development
          region: south
    workers:
      nodePools:
        - name: wp
          taint: []
          version: "1.35.0"
          replicas: 2
          machineClass: medium # Should provide 2 vCPUs, 2 GiB RAM
          autoscaling:
            enabled: false
            minReplicas: 1
            maxReplicas: 5
            scalingRules:
              - "cpu"
          metadata:
            annotations:
              environment: development
              region: south
            labels:
              environment: development
              region: south
          provider: kubevirt
          storage:
            - class: "standard"
              path: "/var/lib/vitistack/kubevirt"
              size: "20Gi" # Talos recommended for production
