---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines/status
  verbs:
  - get
- apiGroups:
  - vitistack.io
  resources:
  - kubernetesclusters
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vitistack.io
  resources:
  - kubernetesclusters/finalizers
  verbs:
  - update
- apiGroups:
  - vitistack.io
  resources:
  - kubernetesclusters/status
  - machines/status
  verbs:
  - get
  - patch
  - update
