package consts

var (
	LOG_LEVEL                       = "LOG_LEVEL"
	LOG_JSON                        = "LOG_JSON"
	LOG_ADD_CALLER                  = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE          = "LOG_DISABLE_STACKTRACE"
	LOG_UNESCAPED_MULTILINE         = "LOG_UNESCAPED_MULTILINE"
	LOG_COLORIZE_LINE               = "LOG_COLORIZE_LINE"
	SECRET_PREFIX                   = "SECRET_PREFIX"
	TENANT_CONFIGMAP_NAME           = "TENANT_CONFIGMAP_NAME"
	TENANT_CONFIGMAP_NAMESPACE      = "TENANT_CONFIGMAP_NAMESPACE"
	TENANT_CONFIGMAP_DATA_KEY       = "TENANT_CONFIGMAP_DATA_KEY"
	TALOS_VM_INSTALL_IMAGE_KUBEVIRT = "TALOS_VM_INSTALL_IMAGE_KUBEVIRT"
	TALOS_VM_INSTALL_IMAGE_DEFAULT  = "TALOS_VM_INSTALL_IMAGE_DEFAULT"
	TALOS_PREDICTABLE_NETWORK_NAMES = "TALOS_PREDICTABLE_NETWORK_NAMES"
	VITISTACK_NAME                  = "VITISTACK_NAME"
	NAME_KUBERNETES_PROVIDER        = "NAME_KUBERNETES_PROVIDER"
)
