package consts

var (
	PERSIST_MACHINE_MANIFESTS         = "PERSIST_MACHINE_MANIFESTS"
	PERSIST_MACHINE_MANIFESTS_DEFAULT = true
	MACHINE_MANIFESTS_PATH            = "MACHINE_MANIFESTS_PATH"
	TALOS_CONFIG_BASE_PATH            = "TALOS_CONFIG_BASE_PATH"
	JSON_LOGGING                      = "JSON_LOGGING"
	LOG_LEVEL                         = "LOG_LEVEL"
	SECRET_PREFIX                     = "SECRET_PREFIX"
	TENANT_CONFIGMAP_NAME             = "TENANT_CONFIGMAP_NAME"
	TENANT_CONFIGMAP_NAMESPACE        = "TENANT_CONFIGMAP_NAMESPACE"
	TENANT_CONFIGMAP_DATA_KEY         = "TENANT_CONFIGMAP_DATA_KEY"
	// Virtual machine Talos install images
	TALOS_VM_INSTALL_IMAGE_PROXMOX    = "TALOS_VM_INSTALL_IMAGE_PROXMOX"
	TALOS_VM_INSTALL_IMAGE_KUBEVIRT   = "TALOS_VM_INSTALL_IMAGE_KUBEVIRT"
	TALOS_VM_INSTALL_IMAGE_LIBVIRT    = "TALOS_VM_INSTALL_IMAGE_LIBVIRT"
	TALOS_VM_INSTALL_IMAGE_KVM        = "TALOS_VM_INSTALL_IMAGE_KVM"
	TALOS_VM_INSTALL_IMAGE_VMWARE     = "TALOS_VM_INSTALL_IMAGE_VMWARE"
	TALOS_VM_INSTALL_IMAGE_VIRTUALBOX = "TALOS_VM_INSTALL_IMAGE_VIRTUALBOX"
	TALOS_VM_INSTALL_IMAGE_HYPERV     = "TALOS_VM_INSTALL_IMAGE_HYPERV"
	TALOS_VM_INSTALL_IMAGE_DEFAULT    = "TALOS_VM_INSTALL_IMAGE_DEFAULT"
)
