apiVersion: vitistack.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: t-test-004-43ss
spec:
  data:
    clusterUid: "a30fbc8d-596f-48d0-8541-dbc23bca28a1"
    clusterId: "t-test-004-43ss"
    provider: talos
    environment: dev
    datacenter: test-south-az1
    project: simple-project
    region: south
    workorder: "simple-workorder"
    zone: "az1"
    workspace: "simple-workspace"
  # High-availability configuration with Talos recommended specifications:
  # Control Plane: 4 GiB RAM, 4 CPUs, 100 GiB disk
  # Workers: 2 GiB RAM, 2 CPUs, 100 GiB disk
  topology:
    version: "1.35.0"
    controlplane:
      replicas: 1
      version: "1.35.0"
      machineClass: small # Should provide 4 vCPUs, 4 GiB RAM
      provider: kubevirt
      storage:
        - class: "standard"
          path: "/var/lib/vitistack/kubevirt"
          size: "50Gi" # Talos recommended for production
      metadata:
        annotations:
          environment: development
          region: west-trondelag
        labels:
          environment: development
          region: west-trondelag
    workers:
      nodePools:
        - name: wp
          taint: []
          version: "1.35.0"
          replicas: 1
          machineClass: large
          autoscaling:
            enabled: false
            minReplicas: 1
            maxReplicas: 5
            scalingRules:
              - "cpu"
          metadata:
            annotations:
              environment: development
              region: west-trondelag
            labels:
              environment: development
              region: west-trondelag
          provider: kubevirt
          storage:
            - class: "standard"
              path: "/var/lib/vitistack/kubevirt"
              size: "50Gi" # Talos recommended for production
