apiVersion: vitistack.io/v1alpha1
kind: NetworkNamespace
metadata:
  name: team-viti2
spec:
  datacenterIdentifier: test-south-az1
  supervisorIdentifier: test-viti
  ipAllocation:
    type: dhcp
    provider: kea
    dhcp:
      requireClientClasses:
        - biosclients
        - ueficlients
        - ipxeclients