---
apiVersion: vitistack.io/v1alpha1
kind: MachineClass
metadata:
  name: small
spec:
  displayName: Small
  description: Small instance with 2 cores and 8Gi memory
  enabled: true
  default: false
  category: Standard
  cpu:
    cores: 2
    sockets: 1
    threads: 1
  memory:
    quantity: 4Gi
  machineProviders: []
---
apiVersion: vitistack.io/v1alpha1
kind: MachineClass
metadata:
  name: medium
spec:
  displayName: Medium
  description: Medium instance with 4 cores and 16Gi memory
  enabled: true
  default: true
  category: Standard
  cpu:
    cores: 4
    sockets: 1
    threads: 1
  memory:
    quantity: 6Gi
  machineProviders: []
